Add support for variations for free downloads
easydigitaldownloads/edd-license-free-download pull request #12
Opened 2020-09-22 15:48 UTC by robincornett

Fixes #4

2020-09-23 12:17 UTC, ashleyfae requested changes
I selected "Software Licensing - Variable Priced Plugin: Single Site", but after saving and refreshing, it looks like this:

![Screenshot from 2020-09-23 13-13-27](https://user-images.githubusercontent.com/6324272/94011303-101a2e00-fd9f-11ea-97e7-83a3e7707513.png)

2020-09-23 14:49 UTC, robincornett commented
So this needs some more thinking for the front end use and validation. I think I need to hold off until #6 is resolved, because right now validation isn't working at all without it, but the validation is looking for a product ID, and this saves the product ID with the price ID appended, so the matches no longer match.

2020-09-23 15:40 UTC, ashleyfae commented
Yeah I had that same thought, but didn't want to dig into it without #6. :+1:

2020-10-09 19:41 UTC, mihaijoldis approved these changes

2020-10-29 14:31 UTC, ashleyfae commented on edd-license-free-download.php
> +					$products[] = esc_attr( $product );
Maybe `sanitize_text_field()` is better here?

Typically you want `sanitize_{x}` when _saving data_ and `esc_{x}` when _displaying_ data. We're saving here, so a sanitize option is better.

2020-10-29 14:53 UTC, ashleyfae commented
## Tested

- [x] Same product, different variation cannot access.
- [x] Same product, same variation can access.
- [x] If Free License product doesn't specify a variation, someone who purchases a variation can access.

2020-10-29 14:54 UTC, ashleyfae approved these changes

2020-10-29 14:54 UTC, merged